import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { connectWallet } from '../components/web3connect';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {

    const router = useRouter()

    useEffect(() => {
        const checkauth = setInterval(() => {
            verifyUser()
        }, 2000)
        return () => clearInterval(checkauth)
    })

    async function verifyUser() {
        const output = await connectWallet()
        if (output === 0) {
          router.push('/denied')
        }
        else {
          router.push('/welcome')
        }
      }
    

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome!
        </h1>
      </main>
    </div>
  )
}
